version: '3'

services: 

  back:
    build: ./back_express
    container_name: back-end
    restart: always
    ports: 
      - "5000:5000"

    depends_on:
      db: 
        condition: service_healthy



  front:
    # build: ./front_react
    image: nginx:latest
    restart: always
    ports: 
      - "80:80"
    container_name: nginx-front
    volumes:
      - ./build-react:/usr/share/nginx/html 


  db:
    image: postgres
    container_name: postgre-db
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # it saves postgers data to container 
      - ./data:/var/lib/postgresql/data
    healthcheck: # it is for starting or for initialize data base
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5


  adminer:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_DEFAULT_EMAIL: ilya.mishkov@gmail.com
    depends_on:  
      db: 
        condition: service_healthy

    
volumes:
  pgdata:
      